host: 0.0.0.0
url: "https://nhstudio.ru"
plugins:
  - jekyll-seo-tag

collections:
  services:
    output: true
    permalink: /:collection/:name

  portfolio:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default

  - scope:
      path: ""
      type: services
    values:
      layout: default

  - scope:
      path: ""
      type: portfolio
    values:
      layout: default