host: 0.0.0.0
url: "https://nhstudio.ru"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

title: Nice home studio
lang: ru_RU

collections:
  services:
    output: true
    permalink: /:collection/:name

  portfolio:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default

  - scope:
      path: ""
      type: services
    values:
      layout: default

  - scope:
      path: ""
      type: portfolio
    values:
      layout: default