host: 0.0.0.0

collections:
  services:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default

  - scope:
      path: ""
      type: services
    values:
      layout: default